### ISSUE TITLE
There was a problem compiling...

### ISSUE THREAD

**Issue by mickeyboss123** [poikilos/marlininfo#18]
There was a problem compiling

Marlin\src\lcd\marlinui.cpp: In static member function 'static void ManualMove::task()':
Marlin\src\lcd\marlinui.cpp:770:60: error: 'manual_feedrate_mm_s' was not declared in this scope; did you mean 'feedrate_mm_s'?
  770 |         const feedRate_t fr_mm_s = (axis < LOGICAL_AXES) ? manual_feedrate_mm_s[axis] : XY_PROBE_FEEDRATE_MM_S;
      |                                                            ^~~~~~~~~~~~~~~~~~~~
      |                                                            feedrate_mm_s
Compiling .pio\build\LPC1769\src\src\lcd\menu\menu_game.cpp.o
*** [.pio\build\LPC1769\src\src\lcd\marlinui.cpp.o] Error 1
============================================================================ [FAILED] Took 39.47 seconds ============================================================================

**Comment by poikilos** [comment]
What is the configuration version in the version of Marlin you are using? You can see that in the existing Configuration.h file in the Marlin repo you cloned.

What branch of Marlin are you using? This only works with the bugfix branch, which is recommended by the hardware used in the mod.

**Comment by mickeyboss123** [comment]
define CONFIGURATION_H_VERSION 02000903

**Comment by poikilos** [comment]
Ok that's strange. Tell me what commit of Marlin you are using so I can test it. Go to the command line then go to the Marlin directory then do:
```
git log -1
```
- `^` That is a one not an L.

**Comment by mickeyboss123** [comment]
![vs1](https://user-images.githubusercontent.com/1274528/156362112-32a9e281-d149-428f-a714-505268878a08.PNG)

Which version of Marlin should I switch to??

**Comment by poikilos** [comment]
I last used:
```
commit 1b876c170fc62abbb7381cfa79f2456ab4ec48ac (HEAD -> bugfix-2.0.x, origin/bugfix-2.0.x)
Author: Tanguy Pruvot <tpruvot@users.noreply.github.com>
Date:   Thu Dec 23 07:49:15 2021 +0100

    🩹 Fix settings G21 report (#23338)
```

**Comment by poikilos** [comment]
also tested with:
```
commit ecaebe4363b2a817649ca37ae29365d5f1e382f4 (HEAD -> bugfix-2.0.x, origin/bugfix-2.0.x)
Author: Spencer Owen <owenspencer@gmail.com>
Date:   Sat Dec 18 18:58:46 2021 -0700

    ✨ Creality3D V4.2.3 / Ender-2 Pro board (#23307)
```

**Comment by poikilos** [comment]
Ok, as of the last commit, using the marlin-deploy command, you don't need my H files anymore. You can generate an H file from the originals. Steps:
- Go to a terminal
- run `python3 -m pip install --user https://github.com/poikilos/pycodetool/archive/refs/heads/master.zip`
- cd to your copy of Marlin that you want to modify (See "Configure Marlin"). Make a copy of it (you only have to copy the Configuration.h and Configuration_adv.h). Rename the folder to Marlin-R2X_14T so that the deploy script will auto-detect that it is R2X_14T not JGAURORA A3S or some other 3D printer (You can also add the option `--machine R2X_14T` instead).
- cd to the folder containing the copies you made.
- install meld and ensure it is in your system's PATH (so it can be run with `meld` in Terminal without a full path)
- run your copy of marlin-deploy using the full path such as: `python3 /home/owner/git/r2x_14t/marlin-deploy ~/git/Marlin`
  - where ~/git/Marlin is (the real Marlin, not the copy--where you want to compile). Follow additional instructions on screen if there are any issues.
- Meld should launch. If it doesn't, ensure it is installed and in the system or user PATH. You can also view the meld command that was displayed and compare those directories yourself. Potentially, you can just copy the files from the first directory to the next.
- A manual step still necessary for R2X_14T (or BTT boards in general): in platformio.ini, change the default_envs line to `default_envs = LPC1769`
 
I've updated the readme with this information.

It needs testing still, but should work. If you have any other errors you can post them here since this appears to be a version issue. I haven't heard back from you so I'll close this since these instructions should solve just about anything like this now.

**Comment by poikilos** [comment]
There seems to be settings I either added recently or now conflict even in the commit I used before.
